# Lyrics Language Detection & Translation

## 1. Imports & Setup

In [ ]:
import fasttext
import pandas as pd
from time import sleep
from random import randint
from deep_translator import GoogleTranslator
from tqdm.auto import tqdm

tqdm.pandas()

## 2. Basic Cleanup

In [2]:
input_file = 'data/results/tracks_data.csv'
tracks = pd.read_csv(input_file, encoding='utf-8')
lyrics = tracks[tracks['lyrics_text'].notna() & (tracks['lyrics_text'].str.strip() != '')]
lyrics.shape

(50172, 17)

In [3]:
cleaned = lyrics['lyrics_text'].apply(lambda x: re.sub("’", "'", re.sub(r" +", " " , re.sub(r"[\n\r\t]", " ", x))))
lyrics = lyrics.assign(lyrics_clean = cleaned)
lyrics.head(3)

,track_uri,music_title,music_artist,music_album,found_title_spotify,found_album_spotify,found_artist_spotify,found_genius_title,found_genius_artist,genius_track_url,lyrics_language,artist_genres,album_genres,analysis_url,lyrics_text,success,error_message,lyrics_clean
7,1gFNm7cXfG1vSMcxPpSxec,004_The Beatles - Ob-La-Di Ob-La-Da,<unknown>,cd 1,"Ob-La-Di, Ob-La-Da - Remastered 2009",The Beatles (Remastered),The Beatles,"Ob-La-Di, Ob-La-Da",The Beatles,https://genius.com/The-beatles-ob-la-di-ob-la-...,NaN,"['beatlesque', 'british invasion', 'classic ro...",[],https://api.spotify.com/v1/audio-analysis/1gFN...,Desmond has a barrow in the marketplace\nMolly...,True,NaN,Desmond has a barrow in the marketplace Molly ...
8,6j67aNAPeQ31uw4qw4rpLa,005_The Beatles - Wild Honey Pie,<unknown>,cd 1,Wild Honey Pie - Remastered 2009,The Beatles (Remastered),The Beatles,Wild Honey Pie,The Beatles,https://genius.com/The-beatles-wild-honey-pie-...,NaN,"['beatlesque', 'british invasion', 'classic ro...",[],https://api.spotify.com/v1/audio-analysis/6j67...,Honey pie\nHoney pie\n\n\nHoney pie\nHoney pie...,True,NaN,Honey pie Honey pie Honey pie Honey pie Honey ...
9,5Z3Rd1fMcaty8g5Pn7yhBQ,006_The Beatles - The Continuing Story of Bungal,<unknown>,cd 1,The Continuing Story Of Bungalow Bill - Remast...,The Beatles (Remastered),The Beatles,The Continuing Story of Bungalow Bill,The Beatles,https://genius.com/The-beatles-the-continuing-...,NaN,"['beatlesque', 'british invasion', 'classic ro...",[],https://api.spotify.com/v1/audio-analysis/5Z3R...,"Hey, Bungalow Bill\nWhat did you kill, Bungalo...",True,NaN,"Hey, Bungalow Bill What did you kill, Bungalow..."

## 3. Language Detection via FastText

In [4]:
# Load the Fasttext pretrained model
PRETRAINED_MODEL_PATH = 'data/lid.176.bin'
model = fasttext.load_model(PRETRAINED_MODEL_PATH)

In [5]:
# Predict language for each lyrics line
lyrics = lyrics.assign(lyrics_language = lyrics['lyrics_clean'].apply(lambda x: model.predict(x)[0][0]))
lyrics.head(3)

,track_uri,music_title,music_artist,music_album,found_title_spotify,found_album_spotify,found_artist_spotify,found_genius_title,found_genius_artist,genius_track_url,lyrics_language,artist_genres,album_genres,analysis_url,lyrics_text,success,error_message,lyrics_clean
7,1gFNm7cXfG1vSMcxPpSxec,004_The Beatles - Ob-La-Di Ob-La-Da,<unknown>,cd 1,"Ob-La-Di, Ob-La-Da - Remastered 2009",The Beatles (Remastered),The Beatles,"Ob-La-Di, Ob-La-Da",The Beatles,https://genius.com/The-beatles-ob-la-di-ob-la-...,__label__en,"['beatlesque', 'british invasion', 'classic ro...",[],https://api.spotify.com/v1/audio-analysis/1gFN...,Desmond has a barrow in the marketplace\nMolly...,True,NaN,Desmond has a barrow in the marketplace Molly ...
8,6j67aNAPeQ31uw4qw4rpLa,005_The Beatles - Wild Honey Pie,<unknown>,cd 1,Wild Honey Pie - Remastered 2009,The Beatles (Remastered),The Beatles,Wild Honey Pie,The Beatles,https://genius.com/The-beatles-wild-honey-pie-...,__label__en,"['beatlesque', 'british invasion', 'classic ro...",[],https://api.spotify.com/v1/audio-analysis/6j67...,Honey pie\nHoney pie\n\n\nHoney pie\nHoney pie...,True,NaN,Honey pie Honey pie Honey pie Honey pie Honey ...
9,5Z3Rd1fMcaty8g5Pn7yhBQ,006_The Beatles - The Continuing Story of Bungal,<unknown>,cd 1,The Continuing Story Of Bungalow Bill - Remast...,The Beatles (Remastered),The Beatles,The Continuing Story of Bungalow Bill,The Beatles,https://genius.com/The-beatles-the-continuing-...,__label__en,"['beatlesque', 'british invasion', 'classic ro...",[],https://api.spotify.com/v1/audio-analysis/5Z3R...,"Hey, Bungalow Bill\nWhat did you kill, Bungalo...",True,NaN,"Hey, Bungalow Bill What did you kill, Bungalow..."

## 4. English vs Non-English Split

In [6]:
# Retrieve songs where complete text is labelled as "english" 
eng_lyrics = lyrics.loc[lyrics['lyrics_language'] == '__label__en']
eng_lyrics.shape

(35478, 18)

In [7]:
# Retrieve non-English songs
oth_lyrics = lyrics.loc[lyrics['lyrics_language'] != '__label__en']
oth_lyrics.shape

(14694, 18)

## 5. Translate Non-English Lyrics

In [8]:
MAX_LEN = 5000  # Max characters for GoogleTranslator

LANG_MAP = {
    'als': 'de',
    'nn': 'no',
    'oc': 'fr',
    'cbk': 'es',
    'ia': 'la',
    'nds': 'de',
    'br': 'fr',
    'sh': 'sr',
    'pms': 'it',
    'bar': 'de',
}

def split_text(text, max_len=MAX_LEN):
    words = text.split()
    chunks = []
    current_chunk = []
    current_len = 0

    for word in words:
        if current_len + len(word) + 1 > max_len:
            chunks.append(" ".join(current_chunk))
            current_chunk = [word]
            current_len = len(word)
        else:
            current_chunk.append(word)
            current_len += len(word) + 1

    if current_chunk:
        chunks.append(" ".join(current_chunk))
    return chunks

def translate_long_text(text, source_lang, target_lang='en'):
    chunks = split_text(text, MAX_LEN)
    translated_chunks = []
    for chunk in chunks:
        translated_chunks.append(
            GoogleTranslator(source=source_lang, target=target_lang).translate(chunk)
        )
    return " ".join(translated_chunks)

def detect_and_translate(row):
    lang = row['lyrics_language'].replace('__label__', '')
    lang = LANG_MAP.get(lang, lang)  # Map dialects to supported langs
    text = row['lyrics_clean']

    if lang != 'en':
        try:
            return translate_long_text(text, source_lang=lang)
        except Exception as e:
            print(f"Translation error for key {row.get('key', 'N/A')}: {e}")
            return text  # Fallback to original if translation fails
    else:
        return text

# Apply translation to all rows
lyrics['lyrics_en'] = lyrics.progress_apply(detect_and_translate, axis=1)

  0%|          | 0/50172 [00:00<?, ?it/s]

Translation error for key N/A: Request exception can happen due to an api connection error. Please check your connection and try again
Translation error for key N/A: Request exception can happen due to an api connection error. Please check your connection and try again
Translation error for key N/A: sequence item 0: expected str instance, NoneType found
Translation error for key N/A: sequence item 0: expected str instance, NoneType found
Translation error for key N/A: sequence item 0: expected str instance, NoneType found
Translation error for key N/A: sequence item 0: expected str instance, NoneType found
Translation error for key N/A: sequence item 0: expected str instance, NoneType found
Translation error for key N/A: he --> No support for the provided language.
Please select on of the supported languages:
{'afrikaans': 'af', 'albanian': 'sq', 'amharic': 'am', 'arabic': 'ar', 'armenian': 'hy', 'assamese': 'as', 'aymara': 'ay', 'azerbaijani': 'az', 'bambara': 'bm', 'basque': 'eu', 'belarusian': 'be', 'bengali': 'bn', 'bhojpuri': 'bho', 'bosnian': 'bs', 'bulgarian': 'bg', 'catalan': 'ca', 'cebuano': 'ceb', 'chichewa': 'ny', 'chinese (simplified)': 'zh-CN', 'chinese (traditional)': 'zh-TW', 'corsican': 'co', 'croatian': 'hr', 'czech': 'cs', 'danish': 'da', 'dhivehi': 'dv', 'dogri': 'doi', 'dutch': 'nl', 'english': 'en', 'esperanto': 'eo', 'estonian': 'et', 'ewe': 'ee', 'filipino': 'tl', 'finnish': 'fi', 'french': 'fr', 'frisian': 'fy', 'galician': 'gl', 'georgian': 'ka', 'german': 'de', 'greek': 'el', 'guarani': 'gn', 'gujarati': 'gu', 'haitian creole': 'ht', 'hausa': 'ha', 'hawaiian': 'haw', 'hebrew': 'iw', 'hindi': 'hi', 'hmong': 'hmn', 'hungarian': 'hu', 'icelandic': 'is', 'igbo': 'ig', 'ilocano': 'ilo', 'indonesian': 'id', 'irish': 'ga', 'italian': 'it', 'japanese': 'ja', 'javanese': 'jw', 'kannada': 'kn', 'kazakh': 'kk', 'khmer': 'km', 'kinyarwanda': 'rw', 'konkani': 'gom', 'korean': 'ko', 'krio': 'kri', 'kurdish (kurmanji)': 'ku', 'kurdish (sorani)': 'ckb', 'kyrgyz': 'ky', 'lao': 'lo', 'latin': 'la', 'latvian': 'lv', 'lingala': 'ln', 'lithuanian': 'lt', 'luganda': 'lg', 'luxembourgish': 'lb', 'macedonian': 'mk', 'maithili': 'mai', 'malagasy': 'mg', 'malay': 'ms', 'malayalam': 'ml', 'maltese': 'mt', 'maori': 'mi', 'marathi': 'mr', 'meiteilon (manipuri)': 'mni-Mtei', 'mizo': 'lus', 'mongolian': 'mn', 'myanmar': 'my', 'nepali': 'ne', 'norwegian': 'no', 'odia (oriya)': 'or', 'oromo': 'om', 'pashto': 'ps', 'persian': 'fa', 'polish': 'pl', 'portuguese': 'pt', 'punjabi': 'pa', 'quechua': 'qu', 'romanian': 'ro', 'russian': 'ru', 'samoan': 'sm', 'sanskrit': 'sa', 'scots gaelic': 'gd', 'sepedi': 'nso', 'serbian': 'sr', 'sesotho': 'st', 'shona': 'sn', 'sindhi': 'sd', 'sinhala': 'si', 'slovak': 'sk', 'slovenian': 'sl', 'somali': 'so', 'spanish': 'es', 'sundanese': 'su', 'swahili': 'sw', 'swedish': 'sv', 'tajik': 'tg', 'tamil': 'ta', 'tatar': 'tt', 'telugu': 'te', 'thai': 'th', 'tigrinya': 'ti', 'tsonga': 'ts', 'turkish': 'tr', 'turkmen': 'tk', 'twi': 'ak', 'ukrainian': 'uk', 'urdu': 'ur', 'uyghur': 'ug', 'uzbek': 'uz', 'vietnamese': 'vi', 'welsh': 'cy', 'xhosa': 'xh', 'yiddish': 'yi', 'yoruba': 'yo', 'zulu': 'zu'}
Translation error for key N/A: sequence item 0: expected str instance, NoneType found
Translation error for key N/A: sequence item 0: expected str instance, NoneType found
Translation error for key N/A: sequence item 0: expected str instance, NoneType found
Translation error for key N/A: Request exception can happen due to an api connection error. Please check your connection and try again
Translation error for key N/A: rafale, te laisse parterre comme dans Gomorra On mangeait le pain sec, pas de sauce Amora, Marseille c'est la mafia, 1.3 la Camorra Avec toi on coupe les ponts c'est définitif, je rêve pas de gros culs, je rêve d'Infinity Elle a des gros seins, cache ça dans ton soutif, elle est trop matrixé un peu comme Trinity Tu veux ma vie ? Prend tout ce qu'il y a avec. J'en veux pas je te la donne Retour d'Hollande, t'es revenu avec 50 grammes, on dirait que t'as fais passer la tonne (Oh comique) Quand t'as rien, pas de pécule, pas de parloir, c'est pas de l'eau la taule (C'est pas de l'eau) Quand t'es dedans, tout le monde tourne le dos et ta gadji fait sa folle Capitale de la drogue, drogue, drogue, yes sir Du Frozen, que ça smoke, smoke, smoke, yes sir C'est le new 13'Organisé, essaie pas de nous rivaliser Et au pire si on vient en grosse équipe, c'est comme ça c'est la cité RS6 plaqué Pologne mais le bolide est allemand Dans tous les dièses ça charbonne, on se fait plaisir après le Khedma Tu nous fais l'ancien, oui zehma celui qui brasse Ça t'as vu au Kyliad avec Assia de Nasdas 1.3, 5.7, Python, pas de Cobra, tout dans la tête fiston, pas de gros bras Tu te colles de partout, tu donnes ton cul, R'key(?) sur R'key(?), tu es dans de beaux draps Securitas dans le Porsche, pas de menta, ça troue des corps chez nous, pas de Van Damme Ça pense à ta mort, y'a pas de renta, et quand t'es parterre y'a pas de mandat C'est le 13, organe électrique, on va te niquer toi et tes piques DP cagoule levée c'est pratique, la prod je la lève, je la cric Pour tout les cafards postés dans le bloc, ça fout des mini-Uzi dans le froc Pour tout les quartiers où y'a la frappe, nous c'est le 13, on est dans le truc Dans le caleçon, des boules, dans le chargeur, des balles Y'a heja déboule, y'a les keufs détalle Marseille danger Malaga, Rotter', Alger, harraga J'détaille, j'détalle, j'ai la dalle, chargé, Arai, bécane go Air Max, T-Max, j'démarre fort, pull crache nique tous tes morts gros Organisés comme des pros, t'es solo, on est trop On a fait TP dans la zone (la, la, la) On a tout niqué pour la somme (la, la, la) On a esquivé les matons (la, la, la) 13'Organisé, personne va nous canaliser Lame aiguisée, je souris comme Adebisi, tu vas souffrir selon les organes visés Fais attention à ton intonation, t'es une salope y'a pas d'autres appellations T'es bon qu'à parler, t'as jamais fait l'action, ils sont pas doués en rap, ils sont doués en fellation Tester ? Vaut mieux éviter. Sans hésiter, je suis venu viser les points vitaux J'ai vu tomber la neige en été, j'vois défiler les chiennes, à croire j'suis un véto Appelle le dieci-siete (17), on arrive, commence à t'inquiéter Toi tu parles de la rue comme si tu y étais, la nuit j'entends chuchoter les métaux En GTS Panamera, dans le ghetto la paix se fait rare Nique aujourd'hui, demain on verra, j'ai coffré les albums dans les Tera Ça passe à l'acte, ça colle, ça appuie, tout le monde sur tes côtés quand t'as le terrain Un peu de love, ça fait le beau-temps la pluie, fais pas confiance, fais pas l'erreur J'suis pas d'ces bâtards la qui courent, plein de phrases à 20K quand c'est bourré Mental en acier, j'réfléchis trois fois, sur un coup de nerf j'allais mourir Allumé, allumé, allumé, c'est la loi de la jungle, tu te fais allumer Y'a trop de traitres et de folles en effet, Marseille oui tu le sais gros c'est animé Faut le cash pour le Riyadh à 'Kech, c'est pour ça que l'instru j'l'a saccage Ils sont moches comme des mecs qui ont vendus la mèche, nous on va la mettre même si ils sont à 10 dans la cage Un 10 pour la route qui nous paie, un 10 en bas de vos écrans y'en a pas On fait bande à part avec l'argent qu'on a pas, et le talent qu'on ment pas Dos à dos comme Kappa, seuls on va soulever la Copa Intégrer le quota, la proc' nous met coupable, avant que les coups partent C'est que du business, la cagoule est noire comme les gants, tellement je bombarde, je vais me faire flasher Ne donnes pas trop tes plans aux gens, en équipe ils viendront pour t'éclater C'est que du business, j'te fais pas confiance, teste moi tu vas voir j'fais pas que chanter Le regard est noir comme les vitres teintées, 280 sur la route, toute Alicante Vroom, vroom, tu entends que le moteur, j'éclate tellement fort qu'elle veut pas me lâcher Boom, boom, juste en bas de la tess, celui qui sort est revenu pour manger La miss elle a pas trouvée le prince charmant, c'est mes rats de la tess qui vont t'aborder De Lyon à Marseille c'est la même rengaine, dégaine noire dans le noir pour vesqui les condés D'or et de platine, le cœur est black, dans la selha, les pus les blocs J'finis l'taff, j'ai repris ça le matin, gros j'vais pas t'apprendre tous les codes C'est paire de Gore et c'est paire d'Oakley, quand tu parles faut en faire autant Quand faut test ça va pas te rater, y'a des hmm qui partent pas à blanc Faut pas quitter le ghetto, y'a un tas de rouleaux sous cello' Nique, mes sapes sont sous scellé quand je recompte du vert, --> Text length need to be between 0 and 5000 characters
Translation error for key N/A: Request exception can happen due to an api connection error. Please check your connection and try again
Translation error for key N/A: Was wir in deinen Träumen suchen? Wir suchen nichts Wir warten Zwischen uns und dir Wälzt die Wogen ungeheuer Ein gefräßiges Ungetüm Da wo wir landen Wenn wir landen Land gewinnen Allein, zu zweit, zu vielen Wie erwartet Wieder warten Was wir in deinen Träumen suchen? Wir suchen nichts Wir warten Wir warten Irgendwo müssen wir ja warten --> No translation was found using the current translator. Try another translator?
Translation error for key N/A: Request exception can happen due to an api connection error. Please check your connection and try again
Translation error for key N/A: Request exception can happen due to an api connection error. Please check your connection and try again
Translation error for key N/A: pirataria vem logo em segundo Eu tinha vários videos, tranks relíquia Confesso, adoro dinheiro, maconha e putaria Sequência da braba no monza... De novo, de novo, de novo Errei a letra, porra! De novo, é assim O próprio, NoChica Tu reconhece minha voz quando ouve Se tentar fica pegado na pista É melhor não... (Rewind) Diniboy: quando pega já era Isso é informação Brisado, não tem como Flagra, ritmo dos crias é assim mesmo, tendeu? Baguncinha nossa no Brasil Grime Show Só os d'raça O próprio, NoChica Tu reconhece minha voz quando ouve Se tentar fica pegado na pista É melhor não mexer com a minha mina Tá maluco, minha tropa é OG Sem medo da vida Necessidades como Lacoste, Nike eu tenho de sobra Quero as marca nova Minha mina com cordão de ouro ia ficar o trem Ela é mó gostosa Aprendi que o dinheiro abre portas Eu sou real mas recebo em dólar Essa braba é direto da endola Meu nome ganhando na casa de apostas Vou amassar um mec ali em Copa O moicano deixou linda aquela xota Brota safada que o pai gosta Minha língua é braba, ela gosta Ritmo dos cria, sempre cheio de gíria Ritmo dos cria, assim eu levo a vida Ritmo dos cria, sempre cheio de gíria Ritmo dos cria, assim eu levo a vida Porra, vem Derxan, vem! Cara quente, sangue frio Postura, curto pavio Brota uma curta e uma longa , caveirão do cano longo A meta é esse carro do ano, nós fomos o puto do ano Compramo a puta e ser dono Eu patrocinei meus panos Vou botar um preço nos planos Tu não sustenta meus danos, ela sentando no... Calma só tô começando Hoje mesmo terminamos Pode ficar com meus manos, garanto eu não tô ligando Carga nova, rima nova (Rewind) Descontrolado, trem bala sem freio Eles parado são carro enguiçado Semblante do mal, com a cor que dá medo Amante do caos e anseios caros Guerras de ego, esquinas podres Drogas no morro, brigas de bairro Jovens perdidos, dias do caçador E a presa na mesa enfeitando o prato Águia sobrevoa e pesa o ferro Cidade de Deus que vê o inferno Anjos rebelados contra o Estado Só Deus pode julgar os pecados Fácil escolher o lado certo Enfia a tua patente e o diploma no Ruas que eu ando me deram um mestrado Fala mais alto, 'to acostumado Com tiros e fogos, corpos baleados Ê, no final do baile Quem que fica? Quem que corre? No final do baile Não é só balão e Ballantine's Preço caro nessa vida, eu pago e aproveito a viagem Ê, no final do baile Quem que fica? Quem que corre? No final do baile Não é só balão e Ballantine's Preço caro, nessa vida, eu pago e aproveito a viagem G3 de luneta no porte do pai De raça na pista, tropa do mantém Por mancada e dinheiro que muitos se vai Respeito e conceito é com luta que vem Roubar na favela vai ficar de exemplo Pega tua visão, menor emocionado Anda na risca, segue o mandamento O certo é o certo, errado é cobrado Glock de roupa, pente de tambor Vários calibre faz a contenção Vendendo drogas a todo vapor Favela ritmada na melhor gestão Dia de baile o clima 'tá propício Ouro no pescoço, jacaré no peito Ela se amarra no bigode fino Baguncinha, baguncinha Rebobina, Dini? Rebobina então! Dia de guerra o pau quebra Dança valsa com o capeta De meiota adaptado Mira laser e luneta Mira na testa dos cana Acerta a porra da orelha Do alemão ranca' tudo Braço, peito e cabeça Os te****** passa mal Na internet é só ibope Na bala arruma nada Pede ajuda do choque Pode entra que nessa porra e só moleque tiroteio Tem AK, tem Parafal, g3zao rasga no meio Armamento do irã, irã Moda Síria, talibã Peita a tropa do homem Que nos troca até amanhã Tá pensando que essa porra aqui é Call of Duty Olha a porra da internet vários vídeo no Youtube É que os amigo tá pesado, é bala no blindado E fé, fé, fé (Rewind) Rebobina, porra! Oi, oi, oi... É que no pique da embala Nós tá regado de droga Corta giro na favela To passando de XJ Rebola e joga na cara Quando ve nós de passagem Ouro e camisa de time Banheira de hidromassagem Só as melhores suítes Ela rende e insiste Senta, senta na piroca Até ontem ela era virgem Hoje em dia ela se perde Quando vê fica maluca 4 pente no suporte 2 pistola na... (cintura) Toma, toma, toma Senta, senta, senta De Bonsucesso até a Penha, oi De Bonsucesso até a Penha, oi Toma, toma, toma Senta, senta, senta Do Parque União até a Penha Da Nova Holanda... Jogando o campeonato, em todas as linhas eu sou campeão Campe, campe, não tô de camper/ (Rewind) Aí, pra cima Jogando o campeonato, em todas as linhas eu sou campeão Campe, campe, não tô de camper Letal nas linha, eu sou campeão Campe, campe, campeão Porque eu venci na vida eu sou campeão Campe, campe, campeão, campeão, campeão Jogando o campeonato, em todas as linhas eu sou campeão Campe, campe, não tô de camper Letal nas linha, eu sou campeão Campe, campe, campeão Porque eu venci na vida eu sou campeão Campe, campe, campeão, campeão, campeão Junto com meus irmão, tô' montando a firma Eu sou campeão na minha mão, eu sou ancião Só cavar mas nunca acharão Humildade e fé só mantém de pé Não me pegaram, foguete sem ré Não me pegaram porque... Faço --> Text length need to be between 0 and 5000 characters
Translation error for key N/A: zh --> No support for the provided language.
Please select on of the supported languages:
{'afrikaans': 'af', 'albanian': 'sq', 'amharic': 'am', 'arabic': 'ar', 'armenian': 'hy', 'assamese': 'as', 'aymara': 'ay', 'azerbaijani': 'az', 'bambara': 'bm', 'basque': 'eu', 'belarusian': 'be', 'bengali': 'bn', 'bhojpuri': 'bho', 'bosnian': 'bs', 'bulgarian': 'bg', 'catalan': 'ca', 'cebuano': 'ceb', 'chichewa': 'ny', 'chinese (simplified)': 'zh-CN', 'chinese (traditional)': 'zh-TW', 'corsican': 'co', 'croatian': 'hr', 'czech': 'cs', 'danish': 'da', 'dhivehi': 'dv', 'dogri': 'doi', 'dutch': 'nl', 'english': 'en', 'esperanto': 'eo', 'estonian': 'et', 'ewe': 'ee', 'filipino': 'tl', 'finnish': 'fi', 'french': 'fr', 'frisian': 'fy', 'galician': 'gl', 'georgian': 'ka', 'german': 'de', 'greek': 'el', 'guarani': 'gn', 'gujarati': 'gu', 'haitian creole': 'ht', 'hausa': 'ha', 'hawaiian': 'haw', 'hebrew': 'iw', 'hindi': 'hi', 'hmong': 'hmn', 'hungarian': 'hu', 'icelandic': 'is', 'igbo': 'ig', 'ilocano': 'ilo', 'indonesian': 'id', 'irish': 'ga', 'italian': 'it', 'japanese': 'ja', 'javanese': 'jw', 'kannada': 'kn', 'kazakh': 'kk', 'khmer': 'km', 'kinyarwanda': 'rw', 'konkani': 'gom', 'korean': 'ko', 'krio': 'kri', 'kurdish (kurmanji)': 'ku', 'kurdish (sorani)': 'ckb', 'kyrgyz': 'ky', 'lao': 'lo', 'latin': 'la', 'latvian': 'lv', 'lingala': 'ln', 'lithuanian': 'lt', 'luganda': 'lg', 'luxembourgish': 'lb', 'macedonian': 'mk', 'maithili': 'mai', 'malagasy': 'mg', 'malay': 'ms', 'malayalam': 'ml', 'maltese': 'mt', 'maori': 'mi', 'marathi': 'mr', 'meiteilon (manipuri)': 'mni-Mtei', 'mizo': 'lus', 'mongolian': 'mn', 'myanmar': 'my', 'nepali': 'ne', 'norwegian': 'no', 'odia (oriya)': 'or', 'oromo': 'om', 'pashto': 'ps', 'persian': 'fa', 'polish': 'pl', 'portuguese': 'pt', 'punjabi': 'pa', 'quechua': 'qu', 'romanian': 'ro', 'russian': 'ru', 'samoan': 'sm', 'sanskrit': 'sa', 'scots gaelic': 'gd', 'sepedi': 'nso', 'serbian': 'sr', 'sesotho': 'st', 'shona': 'sn', 'sindhi': 'sd', 'sinhala': 'si', 'slovak': 'sk', 'slovenian': 'sl', 'somali': 'so', 'spanish': 'es', 'sundanese': 'su', 'swahili': 'sw', 'swedish': 'sv', 'tajik': 'tg', 'tamil': 'ta', 'tatar': 'tt', 'telugu': 'te', 'thai': 'th', 'tigrinya': 'ti', 'tsonga': 'ts', 'turkish': 'tr', 'turkmen': 'tk', 'twi': 'ak', 'ukrainian': 'uk', 'urdu': 'ur', 'uyghur': 'ug', 'uzbek': 'uz', 'vietnamese': 'vi', 'welsh': 'cy', 'xhosa': 'xh', 'yiddish': 'yi', 'yoruba': 'yo', 'zulu': 'zu'}
Translation error for key N/A: sequence item 0: expected str instance, NoneType found
Translation error for key N/A: Ich lern' Kartentricks und sie liest mir aus Gruselroman'n vor Jede Nacht, bis ich schlafe und dann starten wir von vorn (Ja) Manchmal sagen wir nix und hör'n leise in die Stadt Zieh' an der Zigarette und ich grinse, bis sie lacht Kaufen Vintage-Kram und verlieben uns neu Ich schenk' ihr eine Kleinigkeit und wie sie sich darüber freut (Oh) In den lodrigsten Gassen, auf'm Tritt aus altem Marmor Versteh'n kein Wort, Italienisch kommt uns Spanisch vor Die graue Weisheit imponiert Leben kannste nich' studieren Streicheln Katzen in fremden Fenstern Hinterlassen Tatzen in den Gassen wie Gespenster Uns're Schatten tanzen durch die Ghettos wie zwei Gangster Was wir haben, haben wir auch noch als Rentner Jetzt sitzen wir mit'm Dosenbier in Sardinien auf'm Dach Die Tenöre aus der Stadt schicken bisschen Kitsch mit in die Nacht An jedem ander'n Ort, an jedem anderen Tag Hätten wir die Schönheit satt und schnell wieder kaputt gemacht Die Sonne brennt sich in die Haut und ins Gedächtnis Meine einzige Sorge: dass es nicht echt ist Und barfuß bin ich hart verweichlicht Aber ich glaub', hier wurd' Aristocats gezeichnet Giovanni sieht aus wie 'n Ronaldo Hält nur deutlich schlechter ein'n Ball hoch Penn'n wieder in der Hängematte weg Lachen Touri-Strände aus und danach geh'n wir ins Bett Kopfsteinpflaster, Oleander Bunte Häuser, Falten hinter Sonnenbrillen Ramschläden an der Straße, frische Tätowierungen, ja Die braune Arme füllen, Plastikschmuck und Müll Der unter Fensterläden durch die Straße weht Flauschebart, in dem Tomatensoße klebt Schatten in den Gäng'n und Sonne auf'm Dachvorsprung Hier könn'n wir der Last entkommen Jetzt sitzen wir mit'm Dosenbier in Sardinien auf'm Dach Die Tenöre aus der Stadt schicken bisschen Kitsch mit in die Nacht An jedem ander'n Ort, an jedem anderen Tag Hätten wir die Schönheit satt und schnell wieder kaputt gemacht Und schnell wieder kaputt gemacht --> No translation was found using the current translator. Try another translator?
Translation error for key N/A: Request exception can happen due to an api connection error. Please check your connection and try again
Translation error for key N/A: he --> No support for the provided language.
Please select on of the supported languages:

In [9]:
output_file = 'data/results/tracks_data_translated.csv'
lyrics.to_csv(output_file, index=False, encoding='utf-8')

print(f"Saved translated dataset with new column 'lyrics_en' to {output_file}")

Saved translated dataset with new column 'lyrics_en' to data/results/tracks_data_translated.csv

In [12]:
# %% [markdown]
# ## 6. Translation Summary

# %%
import pandas as pd

# Load the translated dataset
translated_df = pd.read_csv('data/results/tracks_data_translated.csv', encoding='utf-8')

print("\n=== Translation Summary ===")

# Total rows
total_tracks = len(translated_df)
print(f"Total tracks processed: {total_tracks}")

# How many tracks were originally detected as English
num_en_original = (translated_df['lyrics_language'] == '__label__en').sum()
print(f"Originally English lyrics: {num_en_original}")

# Non-English tracks
num_non_en = total_tracks - num_en_original
print(f"Originally Non-English lyrics: {num_non_en}")

# Count by each detected language
print("\nBreakdown by detected language:")
lang_counts = translated_df['lyrics_language'].value_counts()
for lang, count in lang_counts.items():
    print(f"  {lang.replace('__label__','')}: {count}")

# Check how many have a non-empty translated version
num_translated = (
    (translated_df['lyrics_language'] != '__label__en') &
    translated_df['lyrics_en'].notna() &
    (translated_df['lyrics_en'].str.strip() != '')
).sum()
print(f"\nNon-English tracks that received a translation: {num_translated}")

=== Translation Summary ===
Total tracks processed: 50172
Originally English lyrics: 35478
Originally Non-English lyrics: 14694

Breakdown by detected language:
  en: 35478
  de: 10908
  es: 952
  it: 495
  fr: 477
  ko: 335
  ru: 328
  sv: 218
  pt: 148
  ja: 136
  tr: 90
  nl: 53
  pl: 45
  da: 39
  is: 35
  lt: 35
  fi: 33
  la: 30
  sr: 26
  no: 22
  id: 19
  tl: 18
  ro: 15
  als: 13
  uk: 12
  nn: 12
  he: 12
  el: 10
  bg: 9
  sl: 9
  zh: 9
  hi: 8
  hr: 8
  ar: 8
  cs: 7
  sq: 7
  nds: 6
  vi: 6
  fa: 6
  gl: 6
  hu: 6
  et: 5
  gd: 5
  ms: 4
  ga: 4
  eu: 4
  ku: 4
  sh: 3
  lmo: 3
  bs: 3
  ht: 3
  sw: 3
  pa: 3
  br: 3
  ne: 2
  nap: 2
  lv: 2
  tt: 2
  eo: 2
  oc: 2
  sk: 2
  bn: 2
  sa: 2
  jbo: 1
  su: 1
  be: 1
  mn: 1
  cbk: 1
  am: 1
  af: 1
  pms: 1
  uz: 1
  kk: 1
  hsb: 1
  ia: 1
  bar: 1
  ca: 1
  mg: 1
  as: 1
  hy: 1
  th: 1

Non-English tracks that received a translation: 14694

In [ ]:
import pandas as pd
from deep_translator import GoogleTranslator
from tqdm.auto import tqdm
import os
import csv

tqdm.pandas()

MAX_LEN = 5000  # max chars per chunk for GoogleTranslator

LANG_MAP = {
    'als': 'de',
    'nn': 'no',
    'oc': 'fr',
    'cbk': 'es',
    'ia': 'la',
    'nds': 'de',
    'br': 'fr',
    'sh': 'sr',
    'pms': 'it',
    'bar': 'de',
}


def split_text(text, max_len=MAX_LEN):
    words = text.split()
    chunks = []
    current_chunk = []
    current_len = 0

    for word in words:
        if current_len + len(word) + 1 > max_len:
            chunks.append(" ".join(current_chunk))
            current_chunk = [word]
            current_len = len(word)
        else:
            current_chunk.append(word)
            current_len += len(word) + 1

    if current_chunk:
        chunks.append(" ".join(current_chunk))
    return chunks

def translate_long_text(text, source_lang, target_lang='en'):
    chunks = split_text(text, MAX_LEN)
    translated_chunks = []
    for chunk in chunks:
        translated_chunk = GoogleTranslator(source=source_lang, target=target_lang).translate(chunk)
        translated_chunks.append(translated_chunk)
    return " ".join(translated_chunks)

def detect_and_translate(row):
    lang = row['lyrics_language'].replace('__label__', '')
    text = row['lyrics_clean']
    lang = LANG_MAP.get(lang, lang)

    if lang != 'en':
        try:
            return translate_long_text(text, source_lang=lang)
        except Exception as e:
            print(f"Translation error for key {row['key']}: {e}")
            return text
    else:
        return text

# Parameters
output_file = 'data/track_lyrics_translated.csv'
offset = 0  # set your offset here

# Open the output CSV appropriately
mode = 'w' if offset == 0 else 'a'
header = offset == 0

with open(output_file, mode, newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    if header:
        writer.writerow(['key', 'lyrics', 'lyrics_en'])

    for idx, row in tqdm(lyrics.iterrows(), total=len(lyrics)):
        if idx < offset:
            continue
        translated = detect_and_translate(row)
        writer.writerow([row['key'], row['lyrics'], translated])

  0%|          | 0/42075 [00:00<?, ?it/s]

Translation error for key lyrics:5sT164B7XL4S0h7zLuZyvi: sequence item 0: expected str instance, NoneType found
Translation error for key lyrics:4pq5Sqf6HUJe8B1iyYFh5i: sequence item 0: expected str instance, NoneType found
Translation error for key lyrics:49xGCjApgJYMQavlJg2X6V: sequence item 0: expected str instance, NoneType found
Translation error for key lyrics:2WjYE9tQDHuxe86hXD0cRs: sequence item 0: expected str instance, NoneType found
Translation error for key lyrics:3zglBTVFKirguQYcfcSh7o: zh --> No support for the provided language.
Please select on of the supported languages:
{'afrikaans': 'af', 'albanian': 'sq', 'amharic': 'am', 'arabic': 'ar', 'armenian': 'hy', 'assamese': 'as', 'aymara': 'ay', 'azerbaijani': 'az', 'bambara': 'bm', 'basque': 'eu', 'belarusian': 'be', 'bengali': 'bn', 'bhojpuri': 'bho', 'bosnian': 'bs', 'bulgarian': 'bg', 'catalan': 'ca', 'cebuano': 'ceb', 'chichewa': 'ny', 'chinese (simplified)': 'zh-CN', 'chinese (traditional)': 'zh-TW', 'corsican': 'co', 'croatian': 'hr', 'czech': 'cs', 'danish': 'da', 'dhivehi': 'dv', 'dogri': 'doi', 'dutch': 'nl', 'english': 'en', 'esperanto': 'eo', 'estonian': 'et', 'ewe': 'ee', 'filipino': 'tl', 'finnish': 'fi', 'french': 'fr', 'frisian': 'fy', 'galician': 'gl', 'georgian': 'ka', 'german': 'de', 'greek': 'el', 'guarani': 'gn', 'gujarati': 'gu', 'haitian creole': 'ht', 'hausa': 'ha', 'hawaiian': 'haw', 'hebrew': 'iw', 'hindi': 'hi', 'hmong': 'hmn', 'hungarian': 'hu', 'icelandic': 'is', 'igbo': 'ig', 'ilocano': 'ilo', 'indonesian': 'id', 'irish': 'ga', 'italian': 'it', 'japanese': 'ja', 'javanese': 'jw', 'kannada': 'kn', 'kazakh': 'kk', 'khmer': 'km', 'kinyarwanda': 'rw', 'konkani': 'gom', 'korean': 'ko', 'krio': 'kri', 'kurdish (kurmanji)': 'ku', 'kurdish (sorani)': 'ckb', 'kyrgyz': 'ky', 'lao': 'lo', 'latin': 'la', 'latvian': 'lv', 'lingala': 'ln', 'lithuanian': 'lt', 'luganda': 'lg', 'luxembourgish': 'lb', 'macedonian': 'mk', 'maithili': 'mai', 'malagasy': 'mg', 'malay': 'ms', 'malayalam': 'ml', 'maltese': 'mt', 'maori': 'mi', 'marathi': 'mr', 'meiteilon (manipuri)': 'mni-Mtei', 'mizo': 'lus', 'mongolian': 'mn', 'myanmar': 'my', 'nepali': 'ne', 'norwegian': 'no', 'odia (oriya)': 'or', 'oromo': 'om', 'pashto': 'ps', 'persian': 'fa', 'polish': 'pl', 'portuguese': 'pt', 'punjabi': 'pa', 'quechua': 'qu', 'romanian': 'ro', 'russian': 'ru', 'samoan': 'sm', 'sanskrit': 'sa', 'scots gaelic': 'gd', 'sepedi': 'nso', 'serbian': 'sr', 'sesotho': 'st', 'shona': 'sn', 'sindhi': 'sd', 'sinhala': 'si', 'slovak': 'sk', 'slovenian': 'sl', 'somali': 'so', 'spanish': 'es', 'sundanese': 'su', 'swahili': 'sw', 'swedish': 'sv', 'tajik': 'tg', 'tamil': 'ta', 'tatar': 'tt', 'telugu': 'te', 'thai': 'th', 'tigrinya': 'ti', 'tsonga': 'ts', 'turkish': 'tr', 'turkmen': 'tk', 'twi': 'ak', 'ukrainian': 'uk', 'urdu': 'ur', 'uyghur': 'ug', 'uzbek': 'uz', 'vietnamese': 'vi', 'welsh': 'cy', 'xhosa': 'xh', 'yiddish': 'yi', 'yoruba': 'yo', 'zulu': 'zu'}
Translation error for key lyrics:1q9h9NLQMY5YCard1ovyGT: Request exception can happen due to an api connection error. Please check your connection and try again
Translation error for key lyrics:3EHLrxaUtl1QtDBmpAWV5P: rafale, te laisse parterre comme dans Gomorra On mangeait le pain sec, pas de sauce Amora, Marseille c'est la mafia, 1.3 la Camorra Avec toi on coupe les ponts c'est définitif, je rêve pas de gros culs, je rêve d'Infinity Elle a des gros seins, cache ça dans ton soutif, elle est trop matrixé un peu comme Trinity Tu veux ma vie ? Prend tout ce qu'il y a avec. J'en veux pas je te la donne Retour d'Hollande, t'es revenu avec 50 grammes, on dirait que t'as fais passer la tonne (Oh comique) Quand t'as rien, pas de pécule, pas de parloir, c'est pas de l'eau la taule (C'est pas de l'eau) Quand t'es dedans, tout le monde tourne le dos et ta gadji fait sa folle Capitale de la drogue, drogue, drogue, yes sir Du Frozen, que ça smoke, smoke, smoke, yes sir C'est le new 13'Organisé, essaie pas de nous rivaliser Et au pire si on vient en grosse équipe, c'est comme ça c'est la cité RS6 plaqué Pologne mais le bolide est allemand Dans tous les dièses ça charbonne, on se fait plaisir après le Khedma Tu nous fais l'ancien, oui zehma celui qui brasse Ça t'as vu au Kyliad avec Assia de Nasdas 1.3, 5.7, Python, pas de Cobra, tout dans la tête fiston, pas de gros bras Tu te colles de partout, tu donnes ton cul, R'key(?) sur R'key(?), tu es dans de beaux draps Securitas dans le Porsche, pas de menta, ça troue des corps chez nous, pas de Van Damme Ça pense à ta mort, y'a pas de renta, et quand t'es parterre y'a pas de mandat C'est le 13, organe électrique, on va te niquer toi et tes piques DP cagoule levée c'est pratique, la prod je la lève, je la cric Pour tout les cafards postés dans le bloc, ça fout des mini-Uzi dans le froc Pour tout les quartiers où y'a la frappe, nous c'est le 13, on est dans le truc Dans le caleçon, des boules, dans le chargeur, des balles Y'a heja déboule, y'a les keufs détalle Marseille danger Malaga, Rotter', Alger, harraga J'détaille, j'détalle, j'ai la dalle, chargé, Arai, bécane go Air Max, T-Max, j'démarre fort, pull crache nique tous tes morts gros Organisés comme des pros, t'es solo, on est trop On a fait TP dans la zone (la, la, la) On a tout niqué pour la somme (la, la, la) On a esquivé les matons (la, la, la) 13'Organisé, personne va nous canaliser Lame aiguisée, je souris comme Adebisi, tu vas souffrir selon les organes visés Fais attention à ton intonation, t'es une salope y'a pas d'autres appellations T'es bon qu'à parler, t'as jamais fait l'action, ils sont pas doués en rap, ils sont doués en fellation Tester ? Vaut mieux éviter. Sans hésiter, je suis venu viser les points vitaux J'ai vu tomber la neige en été, j'vois défiler les chiennes, à croire j'suis un véto Appelle le dieci-siete (17), on arrive, commence à t'inquiéter Toi tu parles de la rue comme si tu y étais, la nuit j'entends chuchoter les métaux En GTS Panamera, dans le ghetto la paix se fait rare Nique aujourd'hui, demain on verra, j'ai coffré les albums dans les Tera Ça passe à l'acte, ça colle, ça appuie, tout le monde sur tes côtés quand t'as le terrain Un peu de love, ça fait le beau-temps la pluie, fais pas confiance, fais pas l'erreur J'suis pas d'ces bâtards la qui courent, plein de phrases à 20K quand c'est bourré Mental en acier, j'réfléchis trois fois, sur un coup de nerf j'allais mourir Allumé, allumé, allumé, c'est la loi de la jungle, tu te fais allumer Y'a trop de traitres et de folles en effet, Marseille oui tu le sais gros c'est animé Faut le cash pour le Riyadh à 'Kech, c'est pour ça que l'instru j'l'a saccage Ils sont moches comme des mecs qui ont vendus la mèche, nous on va la mettre même si ils sont à 10 dans la cage Un 10 pour la route qui nous paie, un 10 en bas de vos écrans y'en a pas On fait bande à part avec l'argent qu'on a pas, et le talent qu'on ment pas Dos à dos comme Kappa, seuls on va soulever la Copa Intégrer le quota, la proc' nous met coupable, avant que les coups partent C'est que du business, la cagoule est noire comme les gants, tellement je bombarde, je vais me faire flasher Ne donnes pas trop tes plans aux gens, en équipe ils viendront pour t'éclater C'est que du business, j'te fais pas confiance, teste moi tu vas voir j'fais pas que chanter Le regard est noir comme les vitres teintées, 280 sur la route, toute Alicante Vroom, vroom, tu entends que le moteur, j'éclate tellement fort qu'elle veut pas me lâcher Boom, boom, juste en bas de la tess, celui qui sort est revenu pour manger La miss elle a pas trouvée le prince charmant, c'est mes rats de la tess qui vont t'aborder De Lyon à Marseille c'est la même rengaine, dégaine noire dans le noir pour vesqui les condés D'or et de platine, le cœur est black, dans la selha, les pus les blocs J'finis l'taff, j'ai repris ça le matin, gros j'vais pas t'apprendre tous les codes C'est paire de Gore et c'est paire d'Oakley, quand tu parles faut en faire autant Quand faut test ça va pas te rater, y'a des hmm qui partent pas à blanc Faut pas quitter le ghetto, y'a un tas de rouleaux sous cello' Nique, mes sapes sont sous scellé quand je recompte du vert, --> Text length need to be between 0 and 5000 characters
Translation error for key lyrics:0ftIaUx27vc9K0ztdiZgHf: Weißt du noch im letzten Jahr Weißt du noch, weißt du noch Ein Sonnenstrahl und er war da Weißt du noch So schmeckt der Sommer So schmeckt der Sommer So schmeckt der Sommer So schmeckt der Sommer So schmeckt der Sommer So schmeckt der Sommer Weißt du, was mit uns geschah Weißt du noch, weißt du noch Die wahre Liebe wurde wahr Weißt du noch So schmeckt der Sommer So schmeckt der Sommer So schmeckt der Sommer (So schmeckt der Sommer) So schmeckt der Sommer (So schmeckt der Sommer) So schmeckt der Sommer (So schmeckt der Sommer) So schmeckt der Sommer Wir war'n ein Paar in jenem Sommer Gingen Hand in Hand Und wenn du willst, seh'n wir uns wieder An unserm Strand So schmeckt der Sommer (So schmeckt der Sommer) So schmeckt der Sommer (So schmeckt der Sommer) So schmeckt der Sommer (So schmeckt der Sommer) So schmeckt der Sommer (So schmeckt der Sommer) So schmeckt der Sommer, uh-uh (So schmeckt der Sommer) Oh-woah (So schmeckt der Sommer) Uh-uh-uh (Weiß es noch im nächsten Jahr) ( viel weiter) So schmeckt der Sommer (So schmeckt der Sommer) So schmeckt der Sommer (So schmeckt der Sommer) So schmeckt der Sommer (Weiß es noch im nächsten Jahr) ( viel weiter) (So schmeckt der Sommer) --> No translation was found using the current translator. Try another translator?
Translation error for key lyrics:40LdkY3tDfhOooaQ8bRgVI: sequence item 0: expected str instance, NoneType found
Translation error for key lyrics:5ZIWWFYEiBhL64QnaFCCDp: sequence item 0: expected str instance, NoneType found
Translation error for key lyrics:7MRAlLkWcSbVutUYbbGFnT: zh --> No support for the provided language.
Please select on of the supported languages:
{'afrikaans': 'af', 'albanian': 'sq', 'amharic': 'am', 'arabic': 'ar', 'armenian': 'hy', 'assamese': 'as', 'aymara': 'ay', 'azerbaijani': 'az', 'bambara': 'bm', 'basque': 'eu', 'belarusian': 'be', 'bengali': 'bn', 'bhojpuri': 'bho', 'bosnian': 'bs', 'bulgarian': 'bg', 'catalan': 'ca', 'cebuano': 'ceb', 'chichewa': 'ny', 'chinese (simplified)': 'zh-CN', 'chinese (traditional)': 'zh-TW', 'corsican': 'co', 'croatian': 'hr', 'czech': 'cs', 'danish': 'da', 'dhivehi': 'dv', 'dogri': 'doi', 'dutch': 'nl', 'english': 'en', 'esperanto': 'eo', 'estonian': 'et', 'ewe': 'ee', 'filipino': 'tl', 'finnish': 'fi', 'french': 'fr', 'frisian': 'fy', 'galician': 'gl', 'georgian': 'ka', 'german': 'de', 'greek': 'el', 'guarani': 'gn', 'gujarati': 'gu', 'haitian creole': 'ht', 'hausa': 'ha', 'hawaiian': 'haw', 'hebrew': 'iw', 'hindi': 'hi', 'hmong': 'hmn', 'hungarian': 'hu', 'icelandic': 'is', 'igbo': 'ig', 'ilocano': 'ilo', 'indonesian': 'id', 'irish': 'ga', 'italian': 'it', 'japanese': 'ja', 'javanese': 'jw', 'kannada': 'kn', 'kazakh': 'kk', 'khmer': 'km', 'kinyarwanda': 'rw', 'konkani': 'gom', 'korean': 'ko', 'krio': 'kri', 'kurdish (kurmanji)': 'ku', 'kurdish (sorani)': 'ckb', 'kyrgyz': 'ky', 'lao': 'lo', 'latin': 'la', 'latvian': 'lv', 'lingala': 'ln', 'lithuanian': 'lt', 'luganda': 'lg', 'luxembourgish': 'lb', 'macedonian': 'mk', 'maithili': 'mai', 'malagasy': 'mg', 'malay': 'ms', 'malayalam': 'ml', 'maltese': 'mt', 'maori': 'mi', 'marathi': 'mr', 'meiteilon (manipuri)': 'mni-Mtei', 'mizo': 'lus', 'mongolian': 'mn', 'myanmar': 'my', 'nepali': 'ne', 'norwegian': 'no', 'odia (oriya)': 'or', 'oromo': 'om', 'pashto': 'ps', 'persian': 'fa', 'polish': 'pl', 'portuguese': 'pt', 'punjabi': 'pa', 'quechua': 'qu', 'romanian': 'ro', 'russian': 'ru', 'samoan': 'sm', 'sanskrit': 'sa', 'scots gaelic': 'gd', 'sepedi': 'nso', 'serbian': 'sr', 'sesotho': 'st', 'shona': 'sn', 'sindhi': 'sd', 'sinhala': 'si', 'slovak': 'sk', 'slovenian': 'sl', 'somali': 'so', 'spanish': 'es', 'sundanese': 'su', 'swahili': 'sw', 'swedish': 'sv', 'tajik': 'tg', 'tamil': 'ta', 'tatar': 'tt', 'telugu': 'te', 'thai': 'th', 'tigrinya': 'ti', 'tsonga': 'ts', 'turkish': 'tr', 'turkmen': 'tk', 'twi': 'ak', 'ukrainian': 'uk', 'urdu': 'ur', 'uyghur': 'ug', 'uzbek': 'uz', 'vietnamese': 'vi', 'welsh': 'cy', 'xhosa': 'xh', 'yiddish': 'yi', 'yoruba': 'yo', 'zulu': 'zu'}
Translation error for key lyrics:6UzdVCkdZG4AAndQb4FtXY: he --> No support for the provided language.
Please select on of the supported languages:
{'afrikaans': 'af', 'albanian': 'sq', 'amharic': 'am', 'arabic': 'ar', 'armenian': 'hy', 'assamese': 'as', 'aymara': 'ay', 'azerbaijani': 'az', 'bambara': 'bm', 'basque': 'eu', 'belarusian': 'be', 'bengali': 'bn', 'bhojpuri': 'bho', 'bosnian': 'bs', 'bulgarian': 'bg', 'catalan': 'ca', 'cebuano': 'ceb', 'chichewa': 'ny', 'chinese (simplified)': 'zh-CN', 'chinese (traditional)': 'zh-TW', 'corsican': 'co', 'croatian': 'hr', 'czech': 'cs', 'danish': 'da', 'dhivehi': 'dv', 'dogri': 'doi', 'dutch': 'nl', 'english': 'en', 'esperanto': 'eo', 'estonian': 'et', 'ewe': 'ee', 'filipino': 'tl', 'finnish': 'fi', 'french': 'fr', 'frisian': 'fy', 'galician': 'gl', 'georgian': 'ka', 'german': 'de', 'greek': 'el', 'guarani': 'gn', 'gujarati': 'gu', 'haitian creole': 'ht', 'hausa': 'ha', 'hawaiian': 'haw', 'hebrew': 'iw', 'hindi': 'hi', 'hmong': 'hmn', 'hungarian': 'hu', 'icelandic': 'is', 'igbo': 'ig', 'ilocano': 'ilo', 'indonesian': 'id', 'irish': 'ga', 'italian': 'it', 'japanese': 'ja', 'javanese': 'jw', 'kannada': 'kn', 'kazakh': 'kk', 'khmer': 'km', 'kinyarwanda': 'rw', 'konkani': 'gom', 'korean': 'ko', 'krio': 'kri', 'kurdish (kurmanji)': 'ku', 'kurdish (sorani)': 'ckb', 'kyrgyz': 'ky', 'lao': 'lo', 'latin': 'la', 'latvian': 'lv', 'lingala': 'ln', 'lithuanian': 'lt', 'luganda': 'lg', 'luxembourgish': 'lb', 'macedonian': 'mk', 'maithili': 'mai', 'malagasy': 'mg', 'malay': 'ms', 'malayalam': 'ml', 'maltese': 'mt', 'maori': 'mi', 'marathi': 'mr', 'meiteilon (manipuri)': 'mni-Mtei', 'mizo': 'lus', 'mongolian': 'mn', 'myanmar': 'my', 'nepali': 'ne', 'norwegian': 'no', 'odia (oriya)': 'or', 'oromo': 'om', 'pashto': 'ps', 'persian': 'fa', 'polish': 'pl', 'portuguese': 'pt', 'punjabi': 'pa', 'quechua': 'qu', 'romanian': 'ro', 'russian': 'ru', 'samoan': 'sm', 'sanskrit': 'sa', 'scots gaelic': 'gd', 'sepedi': 'nso', 'serbian': 'sr', 'sesotho': 'st', 'shona': 'sn', 'sindhi': 'sd', 'sinhala': 'si', 'slovak': 'sk', 'slovenian': 'sl', 'somali': 'so', 'spanish': 'es', 'sundanese': 'su', 'swahili': 'sw', 'swedish': 'sv', 'tajik': 'tg', 'tamil': 'ta', 'tatar': 'tt', 'telugu': 'te', 'thai': 'th', 'tigrinya': 'ti', 'tsonga': 'ts', 'turkish': 'tr', 'turkmen': 'tk', 'twi': 'ak', 'ukrainian': 'uk', 'urdu': 'ur', 'uyghur': 'ug', 'uzbek': 'uz', 'vietnamese': 'vi', 'welsh': 'cy', 'xhosa': 'xh', 'yiddish': 'yi', 'yoruba': 'yo', 'zulu': 'zu'}
Translation error for key lyrics:0jeNOHh2s64O3mWOKG8yGE: he --> No support for the provided language.
Please select on of the supported languages:
{'afrikaans': 'af', 'albanian': 'sq', 'amharic': 'am', 'arabic': 'ar', 'armenian': 'hy', 'assamese': 'as', 'aymara': 'ay', 'azerbaijani': 'az', 'bambara': 'bm', 'basque': 'eu', 'belarusian': 'be', 'bengali': 'bn', 'bhojpuri': 'bho', 'bosnian': 'bs', 'bulgarian': 'bg', 'catalan': 'ca', 'cebuano': 'ceb', 'chichewa': 'ny', 'chinese (simplified)': 'zh-CN', 'chinese (traditional)': 'zh-TW', 'corsican': 'co', 'croatian': 'hr', 'czech': 'cs', 'danish': 'da', 'dhivehi': 'dv', 'dogri': 'doi', 'dutch': 'nl', 'english': 'en', 'esperanto': 'eo', 'estonian': 'et', 'ewe': 'ee', 'filipino': 'tl', 'finnish': 'fi', 'french': 'fr', 'frisian': 'fy', 'galician': 'gl', 'georgian': 'ka', 'german': 'de', 'greek': 'el', 'guarani': 'gn', 'gujarati': 'gu', 'haitian creole': 'ht', 'hausa': 'ha', 'hawaiian': 'haw', 'hebrew': 'iw', 'hindi': 'hi', 'hmong': 'hmn', 'hungarian': 'hu', 'icelandic': 'is', 'igbo': 'ig', 'ilocano': 'ilo', 'indonesian': 'id', 'irish': 'ga', 'italian': 'it', 'japanese': 'ja', 'javanese': 'jw', 'kannada': 'kn', 'kazakh': 'kk', 'khmer': 'km', 'kinyarwanda': 'rw', 'konkani': 'gom', 'korean': 'ko', 'krio': 'kri', 'kurdish (kurmanji)': 'ku', 'kurdish (sorani)': 'ckb', 'kyrgyz': 'ky', 'lao': 'lo', 'latin': 'la', 'latvian': 'lv', 'lingala': 'ln', 'lithuanian': 'lt', 'luganda': 'lg', 'luxembourgish': 'lb', 'macedonian': 'mk', 'maithili': 'mai', 'malagasy': 'mg', 'malay': 'ms', 'malayalam': 'ml', 'maltese': 'mt', 'maori': 'mi', 'marathi': 'mr', 'meiteilon (manipuri)': 'mni-Mtei', 'mizo': 'lus', 'mongolian': 'mn', 'myanmar': 'my', 'nepali': 'ne', 'norwegian': 'no', 'odia (oriya)': 'or', 'oromo': 'om', 'pashto': 'ps', 'persian': 'fa', 'polish': 'pl', 'portuguese': 'pt', 'punjabi': 'pa', 'quechua': 'qu', 'romanian': 'ro', 'russian': 'ru', 'samoan': 'sm', 'sanskrit': 'sa', 'scots gaelic': 'gd', 'sepedi': 'nso', 'serbian': 'sr', 'sesotho': 'st', 'shona': 'sn', 'sindhi': 'sd', 'sinhala': 'si', 'slovak': 'sk', 'slovenian': 'sl', 'somali': 'so', 'spanish': 'es', 'sundanese': 'su', 'swahili': 'sw', 'swedish': 'sv', 'tajik': 'tg', 'tamil': 'ta', 'tatar': 'tt', 'telugu': 'te', 'thai': 'th', 'tigrinya': 'ti', 'tsonga': 'ts', 'turkish': 'tr', 'turkmen': 'tk', 'twi': 'ak', 'ukrainian': 'uk', 'urdu': 'ur', 'uyghur': 'ug', 'uzbek': 'uz', 'vietnamese': 'vi', 'welsh': 'cy', 'xhosa': 'xh', 'yiddish': 'yi', 'yoruba': 'yo', 'zulu': 'zu'}
Translation error for key lyrics:3DX7kAgJNB5zJTSQrBMslh: he --> No support for the provided language.
Please select on of the supported languages:
{'afrikaans': 'af', 'albanian': 'sq', 'amharic': 'am', 'arabic': 'ar', 'armenian': 'hy', 'assamese': 'as', 'aymara': 'ay', 'azerbaijani': 'az', 'bambara': 'bm', 'basque': 'eu', 'belarusian': 'be', 'bengali': 'bn', 'bhojpuri': 'bho', 'bosnian': 'bs', 'bulgarian': 'bg', 'catalan': 'ca', 'cebuano': 'ceb', 'chichewa': 'ny', 'chinese (simplified)': 'zh-CN', 'chinese (traditional)': 'zh-TW', 'corsican': 'co', 'croatian': 'hr', 'czech': 'cs', 'danish': 'da', 'dhivehi': 'dv', 'dogri': 'doi', 'dutch': 'nl', 'english': 'en', 'esperanto': 'eo', 'estonian': 'et', 'ewe': 'ee', 'filipino': 'tl', 'finnish': 'fi', 'french': 'fr', 'frisian': 'fy', 'galician': 'gl', 'georgian': 'ka', 'german': 'de', 'greek': 'el', 'guarani': 'gn', 'gujarati': 'gu', 'haitian creole': 'ht', 'hausa': 'ha', 'hawaiian': 'haw', 'hebrew': 'iw', 'hindi': 'hi', 'hmong': 'hmn', 'hungarian': 'hu', 'icelandic': 'is', 'igbo': 'ig', 'ilocano': 'ilo', 'indonesian': 'id', 'irish': 'ga', 'italian': 'it', 'japanese': 'ja', 'javanese': 'jw', 'kannada': 'kn', 'kazakh': 'kk', 'khmer': 'km', 'kinyarwanda': 'rw', 'konkani': 'gom', 'korean': 'ko', 'krio': 'kri', 'kurdish (kurmanji)': 'ku', 'kurdish (sorani)': 'ckb', 'kyrgyz': 'ky', 'lao': 'lo', 'latin': 'la', 'latvian': 'lv', 'lingala': 'ln', 'lithuanian': 'lt', 'luganda': 'lg', 'luxembourgish': 'lb', 'macedonian': 'mk', 'maithili': 'mai', 'malagasy': 'mg', 'malay': 'ms', 'malayalam': 'ml', 'maltese': 'mt', 'maori': 'mi', 'marathi': 'mr', 'meiteilon (manipuri)': 'mni-Mtei', 'mizo': 'lus', 'mongolian': 'mn', 'myanmar': 'my', 'nepali': 'ne', 'norwegian': 'no', 'odia (oriya)': 'or', 'oromo': 'om', 'pashto': 'ps', 'persian': 'fa', 'polish': 'pl', 'portuguese': 'pt', 'punjabi': 'pa', 'quechua': 'qu', 'romanian': 'ro', 'russian': 'ru', 'samoan': 'sm', 'sanskrit': 'sa', 'scots gaelic': 'gd', 'sepedi': 'nso', 'serbian': 'sr', 'sesotho': 'st', 'shona': 'sn', 'sindhi': 'sd', 'sinhala': 'si', 'slovak': 'sk', 'slovenian': 'sl', 'somali': 'so', 'spanish': 'es', 'sundanese': 'su', 'swahili': 'sw', 'swedish': 'sv', 'tajik': 'tg', 'tamil': 'ta', 'tatar': 'tt', 'telugu': 'te', 'thai': 'th', 'tigrinya': 'ti', 'tsonga': 'ts', 'turkish': 'tr', 'turkmen': 'tk', 'twi': 'ak', 'ukrainian': 'uk', 'urdu': 'ur', 'uyghur': 'ug', 'uzbek': 'uz', 'vietnamese': 'vi', 'welsh': 'cy', 'xhosa': 'xh', 'yiddish': 'yi', 'yoruba': 'yo', 'zulu': 'zu'}
Translation error for key lyrics:2J3uaa6V8FyxNBnpOagaTQ: he --> No support for the provided language.
Please select on of the supported languages:

In [ ]:
# View example translations
lyrics.loc[lyrics['full_lyrics'] != '__label__en'][['lyrics', 'lyrics_en']].head(10)

## 6. Save Translated Output

In [ ]:
output_translated_file = 'data/results/track_lyrics_translated.csv'
lyrics[['key','lyrics', 'lyrics_en']].to_csv(output_translated_file, index=False, encoding='utf-8')